name: Build ChatKita

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: ChatKita_Project
          path: |
            ChatKita_P1.zip
            ChatKita_P2.zip
            ChatKita_P3.zip
